name: Terraform Backend Deployment

on:
 workflow_dispatch:

permissions:
 id-token: write
 contents: read

env:
  TF_WORKING_DIR: ./backend

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      # ---------------------------
      # Checkout
      # ---------------------------
      - name: Checkout
        uses: actions/checkout@v4

      # ---------------------------
      # Azure Login (OIDC)
      # ---------------------------
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # ---------------------------
      # Setup Terraform
      # ---------------------------
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # ---------------------------
      # Terraform Init
      # ---------------------------
      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init -reconfigure

      # ---------------------------
      # Terraform Validate
      # ---------------------------
    #   - name: Terraform Validate
    #     working-directory: ${{ env.TF_WORKING_DIR }}
    #     run: terraform validate

      # ---------------------------
      # Terraform Plan
      # ---------------------------
      - name: Terraform Plan
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform plan -out=tfplan

      # ---------------------------
      # Terraform Apply
      # ---------------------------
      - name: Terraform Apply
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform apply -auto-approve tfplan
